stages:
  - environment
  - check
  - test

default:
  cache: &cache
    key:
      files:
        - environment.yml
    paths:
      - .env/
    policy: pull-push


environment-setup:
  image: continuumio/miniconda3:latest
  stage: environment
  cache:
    <<: *cache
    policy: push
  script:
    - conda env create -f environment.yml -p .env/
    - source activate ./.env

check-formatting:
  image: continuumio/miniconda3:latest
  stage: check
  cache:
    <<: *cache
    policy: pull
  needs: 
    - environment-setup
  script:
    - source activate ./.env
    - |
      if ! pre-commit run ; then
        exit 1
      fi

test-simple-ml:
  image: continuumio/miniconda3:latest
  stage: test
  cache:
    <<: *cache
    policy: pull
  needs: 
    - environment-setup
  script:
    - source activate ./.env
    - python run.py --help
